# Alacritty 配置

# 导入主题文件
general.import = [
  "~/.config/alacritty/themes/dracula.toml"
]

# 环境变量
[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
# decorations = "Buttonless"
decorations = "Full"
opacity = 0.7
blur = true
dynamic_padding = true
dynamic_title = true

[terminal]
osc52 = "OnlyCopy"

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Retina" }

[selection]
save_to_clipboard = true


[keyboard]
bindings = [
    # Ctrl+C 拷贝
    { key = "C", mods = "Control", action = "Copy" },

    # Ctrl+Shift+C 发送中断信号（退出程序）
    { key = "C", mods = "Control|Shift", chars = "\u0003" },

    # Ctrl+V 粘贴
    { key = "V", mods = "Control", action = "Paste" }
]
