repos:
  - repo: local
    hooks:
      - id: pangu
        name: pangu
        entry: pangu
        language: system
        types: [markdown]
      - id: mdformat
        name: mdformat
        entry: mdformat
        language: system
        types: [markdown]
      - id: stylua
        name: stylua
        entry: stylua
        language: system
        types: [lua]
        args: ["--check"]
      - id: luacheck
        name: luacheck
        entry: luacheck
        language: system
        types: [lua]
        stages: [manual]
      - id: install-g-claude
        name: install-g-claude
        entry: bash
        args: ["g-claude/install-g-claude.sh", "$CONTEXT7_API_KEY"]
        language: system
        stages: [commit]
        always_run: false
