services:
  font-cdn:
    image: nginx:alpine
    container_name: font-cdn
    volumes:
      - ./fonts:/usr/share/nginx/html/fonts:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    networks:
      - cdn

networks:
  cdn:
    external: true
